// <auto-generated />
using System;
using DUVAS;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.CategoryPriorityPackageRoom", b =>
                {
                    b.Property<int>("CategoryPriorityPackageRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryPriorityPackageRoomId"));

                    b.Property<int>("CategoryPriorityPackageRoomValue")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CategoryPriorityPackageRoomId");

                    b.ToTable("CategoryPriorityPackageRooms");
                });

            modelBuilder.Entity("BusinessObject.CategoryPriorityPackageServicePost", b =>
                {
                    b.Property<int>("CategoryPriorityPackageServicePostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryPriorityPackageServicePostId"));

                    b.Property<int>("CategoryPriorityPackageServicePostValue")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CategoryPriorityPackageServicePostId");

                    b.ToTable("CategoryPriorityPackageServicePosts");
                });

            modelBuilder.Entity("BusinessObject.PriorityPackageRoom", b =>
                {
                    b.Property<int>("PriorityPackageRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityPackageRoomId"));

                    b.Property<int>("CategoryPriorityPackageRoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PriorityPackageRoomId");

                    b.HasIndex("CategoryPriorityPackageRoomId");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("PriorityPackageRooms");
                });

            modelBuilder.Entity("BusinessObject.PriorityPackageServicePost", b =>
                {
                    b.Property<int>("PriorityPackageServicePostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PriorityPackageServicePostId"));

                    b.Property<int>("CategoryPriorityPackageServicePostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ServicePostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PriorityPackageServicePostId");

                    b.HasIndex("CategoryPriorityPackageServicePostId");

                    b.HasIndex("ServicePostId");

                    b.HasIndex("UserId");

                    b.ToTable("PriorityPackageServicePosts");
                });

            modelBuilder.Entity("DUVAS.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Verify")
                        .HasColumnType("bit");

                    b.HasKey("BuildingId");

                    b.HasIndex("UserId");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("DUVAS.CategoryRoom", b =>
                {
                    b.Property<int>("CategoryRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryRoomId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryRoomId");

                    b.ToTable("CategoryRooms");
                });

            modelBuilder.Entity("DUVAS.CategoryService", b =>
                {
                    b.Property<int>("CategoryServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryServiceId"));

                    b.Property<string>("CategoryServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryServiceId");

                    b.ToTable("CategoryServices");
                });

            modelBuilder.Entity("DUVAS.Contract", b =>
                {
                    b.Property<int>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContractId"));

                    b.Property<string>("ContractFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RentalDateTimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RentalDateTimeStart")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("ContractId");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("DUVAS.InsiderTrading", b =>
                {
                    b.Property<int>("InsiderTradingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InsiderTradingId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("InsiderTradingId");

                    b.HasIndex("UserId");

                    b.ToTable("InsiderTradings");
                });

            modelBuilder.Entity("DUVAS.LandlordLicense", b =>
                {
                    b.Property<int>("LandlordLicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandlordLicenseId"));

                    b.Property<string>("AnhCCCDMatSau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnhCCCDMatTruoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CCCD")
                        .HasColumnType("int");

                    b.Property<string>("GiayPhepKinhDoanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LandlordLicenseId");

                    b.HasIndex("UserId");

                    b.ToTable("LandlordLicenses");
                });

            modelBuilder.Entity("DUVAS.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserGetID")
                        .HasColumnType("int");

                    b.Property<int>("UserSendID")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("UserGetID");

                    b.HasIndex("UserSendID");

                    b.ToTable("Message");
                });

            modelBuilder.Entity("DUVAS.RentalList", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<int?>("ContractId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonthForRent")
                        .HasColumnType("int");

                    b.Property<DateTime>("RentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalStatus")
                        .HasColumnType("int");

                    b.Property<int>("RenterID")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("RentalId");

                    b.HasIndex("ContractId");

                    b.HasIndex("RenterID");

                    b.HasIndex("RoomId");

                    b.ToTable("RentalLists");
                });

            modelBuilder.Entity("DUVAS.RentalServiceList", b =>
                {
                    b.Property<int>("RentalServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalServiceId"));

                    b.Property<DateTime?>("AcceppDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RentalDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("RentalServiceStatus")
                        .HasColumnType("int");

                    b.Property<int>("RenterID")
                        .HasColumnType("int");

                    b.Property<int>("ServicePostID")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RentalServiceId");

                    b.HasIndex("ServicePostID");

                    b.HasIndex("UserId");

                    b.ToTable("RentalServiceLists");
                });

            modelBuilder.Entity("DUVAS.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("Feedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<int?>("ServicePostId")
                        .HasColumnType("int");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TransactionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("RoomId");

                    b.HasIndex("ServicePostId");

                    b.HasIndex("TransactionId");

                    b.HasIndex("UserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("DUVAS.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<double>("Acreage")
                        .HasColumnType("float");

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryRoomId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Furniture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Garret")
                        .HasColumnType("bit");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsPermission")
                        .HasColumnType("bit");

                    b.Property<string>("LocationDetail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfBathroom")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfBedroom")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.HasIndex("BuildingId");

                    b.HasIndex("CategoryRoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("DUVAS.RoomLicense", b =>
                {
                    b.Property<int>("RoomLicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomLicenseId"));

                    b.Property<string>("BienBanPCCC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.HasKey("RoomLicenseId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomLicenses");
                });

            modelBuilder.Entity("DUVAS.ServiceFeedback", b =>
                {
                    b.Property<int>("ServiceFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceFeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServicePostId")
                        .HasColumnType("int");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.HasKey("ServiceFeedbackId");

                    b.HasIndex("ServicePostId");

                    b.ToTable("ServiceFeedbacks");
                });

            modelBuilder.Entity("DUVAS.ServiceLicense", b =>
                {
                    b.Property<int>("ServiceLicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceLicenseId"));

                    b.Property<string>("AnhCCCDMatSau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnhCCCDMatTruoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CCCD")
                        .HasColumnType("int");

                    b.Property<string>("GiayPhepChuyenMon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiayPhepKinhDoanh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ServiceLicenseId");

                    b.HasIndex("UserId");

                    b.ToTable("ServiceLicenses");
                });

            modelBuilder.Entity("DUVAS.ServicePost", b =>
                {
                    b.Property<int>("ServicePostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServicePostId"));

                    b.Property<int>("CategoryServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ServicePostId");

                    b.HasIndex("CategoryServiceId");

                    b.HasIndex("UserId");

                    b.ToTable("ServicePosts");
                });

            modelBuilder.Entity("DUVAS.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BankSubAccID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CassoId")
                        .HasColumnType("int");

                    b.Property<string>("CorresponsiveAccount")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorresponsiveBankId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorresponsiveBankName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CorresponsiveName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CusumBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubAccID")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("When")
                        .HasColumnType("datetime2");

                    b.Property<string>("bankAbbreviation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DUVAS.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Money")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleAdmin")
                        .HasColumnType("int");

                    b.Property<int?>("RoleLandlord")
                        .HasColumnType("int");

                    b.Property<int?>("RoleService")
                        .HasColumnType("int");

                    b.Property<int?>("RoleUser")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DUVAS.UserFeedback", b =>
                {
                    b.Property<int>("UserFeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserFeedbackId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Star")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserFeedbackId");

                    b.HasIndex("UserId");

                    b.ToTable("UserFeedbacks");
                });

            modelBuilder.Entity("DUVAS.WithdrawRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TransactionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("WithdrawRequests");
                });

            modelBuilder.Entity("BusinessObject.PriorityPackageRoom", b =>
                {
                    b.HasOne("BusinessObject.CategoryPriorityPackageRoom", "CategoryPriorityPackageRoom")
                        .WithMany("PriorityPackageRooms")
                        .HasForeignKey("CategoryPriorityPackageRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUVAS.Room", "Room")
                        .WithMany("PriorityPackageRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUVAS.User", "User")
                        .WithMany("PriorityPackageRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryPriorityPackageRoom");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.PriorityPackageServicePost", b =>
                {
                    b.HasOne("BusinessObject.CategoryPriorityPackageServicePost", "CategoryPriorityPackageServicePost")
                        .WithMany("PriorityPackageServicePosts")
                        .HasForeignKey("CategoryPriorityPackageServicePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUVAS.ServicePost", "ServicePost")
                        .WithMany("PriorityPackageServicePosts")
                        .HasForeignKey("ServicePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUVAS.User", "User")
                        .WithMany("PriorityPackageServicePosts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoryPriorityPackageServicePost");

                    b.Navigation("ServicePost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.Building", b =>
                {
                    b.HasOne("DUVAS.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.InsiderTrading", b =>
                {
                    b.HasOne("DUVAS.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.LandlordLicense", b =>
                {
                    b.HasOne("DUVAS.User", "User")
                        .WithMany("OwnerLicenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.Message", b =>
                {
                    b.HasOne("DUVAS.User", "UserGet")
                        .WithMany()
                        .HasForeignKey("UserGetID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DUVAS.User", "UserSend")
                        .WithMany()
                        .HasForeignKey("UserSendID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("UserGet");

                    b.Navigation("UserSend");
                });

            modelBuilder.Entity("DUVAS.RentalList", b =>
                {
                    b.HasOne("DUVAS.Contract", "Contract")
                        .WithMany("RentalLists")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DUVAS.User", "User")
                        .WithMany("RentalLists")
                        .HasForeignKey("RenterID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DUVAS.Room", "Room")
                        .WithMany("RentalLists")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contract");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.RentalServiceList", b =>
                {
                    b.HasOne("DUVAS.ServicePost", "ServicePost")
                        .WithMany("RentalServiceLists")
                        .HasForeignKey("ServicePostID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUVAS.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ServicePost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.Report", b =>
                {
                    b.HasOne("DUVAS.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DUVAS.ServicePost", "ServicePost")
                        .WithMany()
                        .HasForeignKey("ServicePostId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DUVAS.Transaction", "Transaction")
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DUVAS.User", "User")
                        .WithMany("Reports")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("ServicePost");

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.Room", b =>
                {
                    b.HasOne("DUVAS.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUVAS.CategoryRoom", "CategoryRoom")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUVAS.User", "User")
                        .WithMany("Rooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("CategoryRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.RoomLicense", b =>
                {
                    b.HasOne("DUVAS.Room", "Room")
                        .WithMany("RoomLicenses")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DUVAS.ServiceFeedback", b =>
                {
                    b.HasOne("DUVAS.ServicePost", "ServicePost")
                        .WithMany("ServiceFeedbacks")
                        .HasForeignKey("ServicePostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePost");
                });

            modelBuilder.Entity("DUVAS.ServiceLicense", b =>
                {
                    b.HasOne("DUVAS.User", "User")
                        .WithMany("ServiceLicenses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.ServicePost", b =>
                {
                    b.HasOne("DUVAS.CategoryService", "CategoryService")
                        .WithMany("ServicePosts")
                        .HasForeignKey("CategoryServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DUVAS.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryService");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.Transaction", b =>
                {
                    b.HasOne("DUVAS.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.UserFeedback", b =>
                {
                    b.HasOne("DUVAS.User", "User")
                        .WithMany("UserFeedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DUVAS.WithdrawRequest", b =>
                {
                    b.HasOne("DUVAS.Transaction", "Transaction")
                        .WithOne()
                        .HasForeignKey("DUVAS.WithdrawRequest", "TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DUVAS.User", "User")
                        .WithMany("WithdrawRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Transaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObject.CategoryPriorityPackageRoom", b =>
                {
                    b.Navigation("PriorityPackageRooms");
                });

            modelBuilder.Entity("BusinessObject.CategoryPriorityPackageServicePost", b =>
                {
                    b.Navigation("PriorityPackageServicePosts");
                });

            modelBuilder.Entity("DUVAS.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DUVAS.CategoryRoom", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DUVAS.CategoryService", b =>
                {
                    b.Navigation("ServicePosts");
                });

            modelBuilder.Entity("DUVAS.Contract", b =>
                {
                    b.Navigation("RentalLists");
                });

            modelBuilder.Entity("DUVAS.Room", b =>
                {
                    b.Navigation("PriorityPackageRooms");

                    b.Navigation("RentalLists");

                    b.Navigation("RoomLicenses");
                });

            modelBuilder.Entity("DUVAS.ServicePost", b =>
                {
                    b.Navigation("PriorityPackageServicePosts");

                    b.Navigation("RentalServiceLists");

                    b.Navigation("ServiceFeedbacks");
                });

            modelBuilder.Entity("DUVAS.User", b =>
                {
                    b.Navigation("OwnerLicenses");

                    b.Navigation("PriorityPackageRooms");

                    b.Navigation("PriorityPackageServicePosts");

                    b.Navigation("RentalLists");

                    b.Navigation("Reports");

                    b.Navigation("Rooms");

                    b.Navigation("ServiceLicenses");

                    b.Navigation("Transactions");

                    b.Navigation("UserFeedbacks");

                    b.Navigation("WithdrawRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
