name: Build and Deploy ASP.NET Core API to Azure Web App - BEDuvas

on:
  push:
    branches:
      - main2
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build with dotnet
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal
        continue-on-error: true

      - name: Publish dotnet
        run: |
          dotnet publish API/API.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp" --no-restore --no-build --no-self-contained
          # Loại bỏ file không cần thiết
          del "${{env.DOTNET_ROOT}}/myapp/*.pdb"
          # Kiểm tra số lượng file
          (dir "${{env.DOTNET_ROOT}}/myapp" -Recurse -File).Count
          # Liệt kê file .dll, .exe, .json, .pdb
          dir "${{env.DOTNET_ROOT}}/myapp" -Recurse -File | Where-Object { $_.Extension -match "\.dll|\.exe|\.json|\.pdb" } | ForEach-Object { $_.FullName }

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BEDuvas'
          slot-name: 'Production'
          package: '${{env.DOTNET_ROOT}}/myapp'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8D9A4FD332CC4DEEA9891046398642D7 }}
